require 'fileutils'
require 'rake/clean'

def latex(who)
  puts
  puts (cmd_string = "pdflatex #{who}")
  rerun = false
  IO.popen(cmd_string){|io|
    while s = io.gets
      puts s
      rerun = true if /rerun/i  =~ s
    end
  }
  latex(who) if rerun
end

def bibtex(who)
  sh "bibtex #{who}"
end

CLEAN.include('*.ps', '*.dvi', '*.log','*.out','**/*.aux', 
              '*.blg','*.bbl','*.toc','*.lot','*.lof','*.nav','*.snm')
NAME = "slides"
MAIN = "#{NAME}.pdf"
TEX = FileList["*.tex"]
DVI = MAIN.ext('.dvi')

desc "The default task : preview version"
task :default => MAIN
file MAIN => DVI
file DVI => TEX

file DVI do     
  latex MAIN.ext('.tex')
  bibtex NAME
  latex MAIN.ext('.tex')
end

desc "Screen resolution compilation"
file MAIN => DVI do
  main_dvi = MAIN.ext('.dvi');
  main_ps = MAIN.ext('.ps');
  sh "dvips -D600 -Z #{main_dvi}"
  sh "ps2pdf #{main_ps}"
end
