task :default => :images

task :images do
  Dir[File.expand_path('../*.gnuplot', __FILE__)].each do |file|
    basename = File.basename(file, '.gnuplot')
    puts `gnuplot #{file}`
    puts `ps2pdf #{basename}.eps`
  end
end
